name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to alex
        run: echo "hello alex"
